progress on build fixing, something like 250 left

diff --git a/packages/linux/system/init/s6-linux-init/BUCK b/packages/linux/system/init/s6-linux-init/BUCK
--- a/packages/linux/system/init/s6-linux-init/BUCK
+++ b/packages/linux/system/init/s6-linux-init/BUCK
@@ -19,16 +19,32 @@ autotools_package(
     description = "Set of tools to create a s6-based init system",
     homepage = "https://skarnet.org/software/s6-linux-init/",
     license = "ISC",
-    configure_args = [
-        "--prefix=/usr",
-        "--libexecdir=/usr/lib/s6-linux-init",
-        "--skeldir=/etc/s6-linux-init/skel",
-        "--enable-shared",
-        "--disable-static",
-        "--with-sysdeps=/usr/lib/skalibs/sysdeps",
-        "--with-include=/usr/include",
-        "--with-lib=/usr/lib",
-    ],
+    # skarnet.org uses non-standard configure - custom src_configure phase
+    src_configure = """
+# Find skalibs in dependency directories
+SKALIBS_DIR=""
+for dir in ${DEP_BASE_DIRS//:/ }; do
+    if [ -d "$dir/usr/lib/skalibs/sysdeps" ]; then
+        SKALIBS_DIR="$dir"
+        break
+    fi
+done
+if [ -z "$SKALIBS_DIR" ]; then
+    echo "ERROR: Could not find skalibs sysdeps directory"
+    exit 1
+fi
+echo "Found skalibs at: $SKALIBS_DIR"
+
+./configure \\
+    --prefix=/usr \\
+    --libexecdir=/usr/lib/s6-linux-init \\
+    --skeldir=/etc/s6-linux-init/skel \\
+    --enable-shared \\
+    --disable-static \\
+    --with-sysdeps="$SKALIBS_DIR/usr/lib/skalibs/sysdeps" \\
+    --with-include="$SKALIBS_DIR/usr/include" \\
+    --with-lib="$SKALIBS_DIR/usr/lib"
+""",
     deps = [
         "//packages/linux/system/init/skalibs:skalibs",
         "//packages/linux/system/init/s6:s6",
diff --git a/packages/linux/system/init/s6/BUCK b/packages/linux/system/init/s6/BUCK
--- a/packages/linux/system/init/s6/BUCK
+++ b/packages/linux/system/init/s6/BUCK
@@ -19,16 +19,33 @@ autotools_package(
     description = "Small and secure supervision software suite",
     homepage = "https://skarnet.org/software/s6/",
     license = "ISC",
-    configure_args = [
-        "--prefix=/usr",
-        "--libexecdir=/usr/lib/s6",
-        "--libdir=/usr/lib",
-        "--enable-shared",
-        "--disable-static",
-        "--with-sysdeps=/usr/lib/skalibs/sysdeps",
-        "--with-include=/usr/include",
-        "--with-lib=/usr/lib",
-    ],
+    # skarnet.org uses non-standard configure - custom src_configure phase
+    src_configure = """
+# Find skalibs in dependency directories
+SKALIBS_DIR=""
+for dir in ${DEP_BASE_DIRS//:/ }; do
+    if [ -d "$dir/usr/lib/skalibs/sysdeps" ]; then
+        SKALIBS_DIR="$dir"
+        break
+    fi
+done
+if [ -z "$SKALIBS_DIR" ]; then
+    echo "ERROR: Could not find skalibs sysdeps directory"
+    echo "DEP_BASE_DIRS: $DEP_BASE_DIRS"
+    exit 1
+fi
+echo "Found skalibs at: $SKALIBS_DIR"
+
+./configure \\
+    --prefix=/usr \\
+    --libexecdir=/usr/lib/s6 \\
+    --libdir=/usr/lib \\
+    --enable-shared \\
+    --disable-static \\
+    --with-sysdeps="$SKALIBS_DIR/usr/lib/skalibs/sysdeps" \\
+    --with-include="$SKALIBS_DIR/usr/include" \\
+    --with-lib="$SKALIBS_DIR/usr/lib"
+""",
     deps = [
         "//packages/linux/system/init/skalibs:skalibs",
     ],
